import { expect, test } from '@playwright/test'

test('default overview is lightweight and opens Guangdong University of Technology', async ({ page }) => {
  const requested = []
  page.on('request', request => requested.push(request.url()))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '广东工业大学' })).toBeVisible()
  await expect(page.getByRole('button', { name: '总览' })).toHaveClass(/active/)
  expect(requested.some(url => url.includes('/heatmaps/'))).toBeFalsy()
  expect(requested.some(url => url.includes('/roles/hero/'))).toBeFalsy()
  expect(requested.some(url => url.includes('/repechage.json'))).toBeFalsy()
  expect(requested.some(url => url.includes('/v4/tactics/'))).toBeFalsy()
})

test('team tabs lazy-load map and comparison data', async ({ page }) => {
  await page.goto('/')
  const heatmap = page.waitForResponse(response => response.url().includes('/heatmaps/'))
  await page.getByRole('button', { name: '地图', exact: true }).click()
  await heatmap
  await expect(page.getByLabel('队伍秒级热力图')).toBeVisible()
  await page.getByRole('button', { name: '对比', exact: true }).click()
  await expect(page.getByText('选择另一支队伍后')).toBeVisible()
})

test('match replay exposes native cadence, interpolated playback and confidence damage layers', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '对局', exact: true }).click()
  await page.locator('.match-grid button').first().click()
  await expect(page.getByText('原始 1.0 Hz · 位置插值 ≤60 FPS')).toBeVisible()
  await expect(page.locator('.scrubber')).toHaveAttribute('step', '.05')
  await expect(page.getByText('发弹脉冲：位置与弹量事实')).toBeVisible()
  await expect(page.getByText('高：扣血位置确认且同秒有敌方发弹')).toBeVisible()
  await expect(page.getByText('中：扣血位置确认、原因不明')).toBeVisible()
  await expect(page.getByText('低：沿用上一有效位置')).toBeVisible()
  await expect(page.getByText('无枪口朝向数据，不绘制推定弹道；判罚扣血已排除')).toBeVisible()
  await expect(page.locator('.damage-feed h3 small')).toHaveText(/\d+ 条/)
  await page.locator('.scrubber').evaluate((input) => { input.value = '12'; input.dispatchEvent(new Event('input', { bubbles: true })) })
  await expect(page.locator('.shot-effect')).not.toHaveCount(0)
  await expect(page.locator('.damage-effect line')).toHaveCount(0)
  await page.locator('.scrubber').evaluate((input) => { input.value = '5'; input.dispatchEvent(new Event('input', { bubbles: true })) })
  await expect(page.locator('.damage-effect')).not.toHaveCount(0)
  await expect(page.locator('.damage-feed button')).not.toHaveCount(0)
})

test('tactics expose concrete match values in addition to scores', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '战术', exact: true }).click()
  await expect(page.getByText('场均总输出')).toBeVisible()
  await expect(page.getByText('4674 点/局')).toBeVisible()
  await expect(page.getByRole('button', { name: '展开详情' })).toHaveCount(6)
  await expect(page.getByText('净输出/对手预期')).toHaveCount(0)
  await page.getByRole('button', { name: '展开详情' }).first().click()
  await expect(page.getByText('净输出/对手预期')).toBeVisible()
  await expect(page.getByText('各分项有效样本 20 局')).toBeVisible()
  await expect(page.getByRole('heading', { name: '阶段动作链' })).toBeVisible()
  await expect(page.locator('.tactical-mode-panel .section-head').getByText(/\d+ 局 · \d+ 个对手 · 17 类模式/)).toBeVisible()
  const firstPattern = page.locator('.tactical-pattern').first()
  await expect(firstPattern.getByText(/局 ·/)).toBeVisible()
  await firstPattern.locator('.pattern-summary').click()
  await expect(firstPattern.getByText('出现时胜率')).toBeVisible()
})

test('tactics generate a detailed two-team counter plan', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '战术', exact: true }).click()
  await page.getByLabel('我方执行队伍').selectOption({ label: '华南农业大学' })
  await expect(page.locator('.counter-matchup-head').getByText('华南农业大学', { exact: true })).toBeVisible()
  await expect(page.locator('.counter-plan-card')).toHaveCount(3)
  const first = page.locator('.counter-plan-card').first()
  await expect(first.getByText('目标威胁')).toBeVisible()
  await expect(first.getByText('我方能力匹配')).toBeVisible()
  await expect(first.getByText('成功')).toBeVisible()
  await expect(first.getByText('退出')).toBeVisible()
  await expect(first.getByText('回退')).toBeVisible()
  await expect(first.getByText('风险')).toBeVisible()
})

test('tactics replace a failed profile request with an actionable retry', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '战术', exact: true }).click()
  const failedProfile = '**/data/v4/tactics/team-788bd487bf857297.json*'
  await page.route(failedProfile, route => route.fulfill({ status: 200, contentType: 'text/html', body: '<!doctype html>' }))
  await page.getByLabel('我方执行队伍').selectOption({ label: '深圳技术大学' })
  await expect(page.getByText('战术画像返回格式错误，请重启开发服务后重试')).toBeVisible()
  await expect(page.getByText('正在匹配双方战术画像…')).toHaveCount(0)
  await page.unroute(failedProfile)
  await page.getByRole('button', { name: '重新加载' }).last().click()
  await expect(page.locator('.counter-plan-card')).toHaveCount(3)
})

test('methodology is contextual and returns focus when closed', async ({ page }) => {
  await page.goto('/')
  const trigger = page.getByRole('button', { name: '数据口径' })
  await trigger.click()
  await expect(page.getByRole('dialog', { name: '数据口径 · 总览' })).toBeVisible()
  await expect(page.getByText('评分阅读')).toBeVisible()
  await expect(page.getByRole('button', { name: '关闭', exact: true })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: '关闭', exact: true })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(trigger).toBeFocused()
})

test('role and tournament navigation remain functional', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '兵种数据' }).click()
  await expect(page.getByRole('heading', { name: /广东工业大学 · 英雄/ })).toBeVisible()
  await expect(page.getByText('逐局兵种表现')).toBeVisible()
  await expect(page.getByText('赛果 / 对手')).toBeVisible()
  await page.getByRole('button', { name: '赛事模拟' }).click()
  await expect(page.getByRole('heading', { name: /赛事模拟/ })).toBeVisible()
  await expect(page.getByText('模拟 · 非官方')).toBeVisible()
})

test('mobile filters open without horizontal page overflow', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  const method = page.getByRole('button', { name: '数据口径' })
  const filter = page.getByRole('button', { name: '筛选', exact: true })
  await expect(method).toBeVisible()
  await expect(filter).toBeVisible()
  const [methodBox, filterBox] = await Promise.all([method.boundingBox(), filter.boundingBox()])
  expect(methodBox.x + methodBox.width).toBeLessThanOrEqual(filterBox.x)
  await filter.click()
  await expect(page.getByText('队伍检索', { exact: true })).toBeVisible()
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)
  expect(overflow).toBeFalsy()
})
